package com.bang.invoice_ver.utils;

import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

/**
 * 
 * Description: 答案
 * 
 * @author wangxinbang
 * @version 1.0
 * 
 * <pre>
 * Modification History: 
 * Date Author  Version Description 
------------------------------------------------------------------
 * 2017年12月10日wangxinbang   1.01.0 Version 
 * </pre>
 */
public enum AnswerEnum {

    the_answer1(1, "需要一个相当大的努力", "A Substantial Effort Will Be Required"),
    the_answer2(2, "从现在开始 一年也没有关系", " A Year From Now It Won't Matter"),
    the_answer3(3, "绝对不是", "Absolutely Not"),
    the_answer4(4, "接受改变你的日常行为", "Accept A Change To Your Routine"),
    the_answer5(5, "似乎已经是真实的了", " Act As Though It Is Already Real"),
    the_answer6(6, "采用一个冒险的态度", "Adopt An Adventurous Attitude"),
    the_answer7(7, "允许你选择先休息一下", "Allow Yoursele To Rest First"),
    the_answer8(8, "小心谨慎的靠近", "Approach Cautiously"),
    the_answer9(9, "你还是问问爸爸吧", " Ask Your Father"),
    the_answer10(10, "你还是问问妈妈吧", "Ask Your Mother"),
    the_answer11(11, "援助会让你成功进步", "Assistance Would Make Your Progress A Success"),
    the_answer12(12, "避免第一个解决方案", "Avoid The First Solution"),
    the_answer13(13, "被人肯定", "Be Delightfully Sure Of It"),
    the_answer14(14, "更慷慨", "Be More Generous"),
    the_answer15(15, "耐心点", "Be Patient"),
    the_answer16(16, "实际一点吧", "Be Practical"),
    the_answer17(17, "打赌", "Bet On It"),
    the_answer18(18, "耐心的等待", "Better To Wait"),
    the_answer19(19, "合作将会是关键", "Collaboration Will Be The Key"),
    the_answer20(20, "考虑一下这个机会", "Consider It An Opportunity"),
    the_answer21(21, "数到10；再问", "Count To 10; Ask Again"),
    the_answer22(22, "以后处理", "Deal With It Later"),
    the_answer23(23, "当然", "Definitely"),
    the_answer24(24, "早点做到这一点", "Do It Early"),
    the_answer25(25, "在这个时候不要问太多了", "Don't Ask For Any More At This Time"),
    the_answer26(26, "不要担心", "Don't Be Concerned"),
    the_answer27(27, "不要迫于压力太快", "Don't Be Pressured Into Acting Too Quickly"),
    the_answer28(28, "别傻了", "Don't Be Ridiculous"),
    the_answer29(29, "不要赌", "Don't Bet On It"),
    the_answer30(30, "不用怀疑了", "Don't Doubt It"),
    the_answer31(31, "不要忘记有乐趣", "Don't Forget To Have Fun"),
    the_answer32(32, "不要陷入你的感情", "Don't Get Caught Up In Your Emotions"),
    the_answer33(33, "不要犹豫", "Don't Hesitate"),
    the_answer34(34, "不要忽视显而易见的", "Don't Ignore The Obvious"),
    the_answer35(35, "不要过分", "Don't Overdo It"),
    the_answer36(36, "不要等待", "Don't Wait"),
    the_answer37(37, "别浪费时间了", "Don't Waste Your Time"),
    the_answer38(38, "怀疑", "Doubt It"),
    the_answer39(39, "尽情体验", "Enjoy The Experience"),
    the_answer40(40, "要解决", "Expect To Settle"),
    the_answer41(41, "探讨其俏皮的好奇心", "Explore It With Playful Curiosity"),
    the_answer42(42, "完成其他事情的第一", "Finish Something Else First"),
    the_answer43(43, "专注你的家庭生活", "Focus On Your Home Life"),
    the_answer44(44, "遵循别人的引导", "Follow Someone Else's Lead"),
    the_answer45(45, "遵循专家的建议", "Follow The Advice Of Experts"),
    the_answer46(46, "履行你自己的义务", "Follow Through On Your Obligations"),
    the_answer47(47, "按照你的意愿", "Follow Through With Your Good Intentions"),
    the_answer48(48, "温柔的坚持就是胜利", "Gentle Persistence Will Pay Off"),
    the_answer49(49, "获得更清晰的视野", "Get A Clearer View"),
    the_answer50(50, "把它写下来", "Get It In Writing"),
    the_answer51(51, "给它你的一切", "Give It All You've Got"),
    the_answer52(52, "如果是，做的很好；如果不是，就不要这么做；", "If It's Done Well; If Not, Don't Do It At All"),
    the_answer53(53, "如果你按我说的做", "If You Do As You're Told"),
    the_answer54(54, "如果你不反抗", "If You Don't Resist"),
    the_answer55(55, "调查研究，然后享受它！", "Investigate And Then Enjoy It"),
    the_answer56(56, "这不可能失败", "It Cannot Fail"),
    the_answer57(57, "这可能是特别的", "It Could Be Extraordinary"),
    the_answer58(58, "这是肯定的", "It Is Certain"),
    the_answer59(59, "这不是重要的", "It Is Not Significant"),
    the_answer60(60, "这是非常重要", "It Is Significant"),
    the_answer61(61, "这是你不会忘记的It", "Is Something You Won't Forget"),
    the_answer62(62, "这肯定会让事情变得有趣", "It Is Sure To Make Things Interesting"),
    the_answer63(63, "这是不确定的", "It Is Uncertain"),
    the_answer64(64, "是值得的麻烦", "It Is Worth The Trouble"),
    the_answer65(65, "这可能已经是木已成舟", "It May Already Be A Done Deal"),
    the_answer66(66, "这可能很难，但你会发现它的价值", "It May Be Difficult But You Will Find Value In It"),
    the_answer67(67, "这个似乎放心", "It Seems Assured"),
    the_answer68(68, "这将影响别人看你", "It Will Affect How Others See You"),
    the_answer69(69, "这将是一种享受", "It Will Be A Pleasure"),
    the_answer70(70, "这会带来好运", "It Will Bring Good Luck"),
    the_answer71(71, "这将会创造一个扰乱", "It Will Create A Stir"),
    the_answer72(72, "这仍然是不可预测的", "It Will Remain Unpredictable"),
    the_answer73(73, "它会支持你的", "It Will Sustain You"),
    the_answer74(74, "这将更好地专注于自己的工作", "It Would Be Better To Focus On Your Work"),
    the_answer75(75, "这是不明智的", "It Would Be Inadvisable"),
    the_answer76(76, "它会让你付出代价", "It'll Cost You"),
    the_answer77(77, "这是一个不错的时间安排", "It's A Good Time To Make Plans"),
    the_answer78(78, "会很棒的", "It's Gonna Be Great"),
    the_answer79(79, "这是不值得的斗争", "It's Not Worth A Struggle"),
    the_answer80(80, "是你走的时候", "It's Time For You To Go"),
    the_answer81(81, "保持开放的心态", "Keep An Open Mind"),
    the_answer82(82, "不要让别人知道", "Keep It To Yourself"),
    the_answer83(83, "笑一下", "Laugh About It"),
    the_answer84(84, "离开旧的解决方案", "Leave Behind Old Solutions"),
    the_answer85(85, "过去的事就让它过去吧", "Let It Go"),
    the_answer86(86, "仔细聆听；那么你就会知道", "Listen More Carefully; Then You Will Know"),
    the_answer87(87, "列出原因", "Make A List Of Why"),
    the_answer88(88, "为什么不列出原因", "Make A List Of Why Not"),
    the_answer89(89, "也许", "Maybe"),
    the_answer90(90, "不幸的是极有可能的", " Mishaps Are Highly Probable"),
    the_answer91(91, "继续前行", "Move On"),
    the_answer92(92, "从来没有", "Never"),
    the_answer93(93, "没有", "No"),
    the_answer94(94, "不管是什么", "No Matter What"),
    the_answer95(95, "如果你不孤单", " Not If You're Alone"),
    the_answer96(96, "现在你可以", "Now You Can"),
    the_answer97(97, "只做一次", "Only Do It Once"),
    the_answer98(98, "其他人将取决于你的选择", "Others Will Depend On Your Choices"),
    the_answer99(99, "注重细节", "Pay Attention To The Details"),
    the_answer100(100, "也许，当你老了", "Perhaps, When You're Older"),
    the_answer101(101, "为突发事件做好准备", "Prepare For The Unexpected"),
    the_answer102(102, "按下关闭", "Press For Closure"),
    the_answer103(103, "须以较宽松的步伐", "Proceed At A More Relaxed Pace"),
    the_answer104(104, "有时候选择太多，就代表着无从选择！", "  Realize That Too Many Choices Is As Difficult As Too Few"),
    the_answer105(105, "重新考虑你的方法", "Reconsider Your Approach"),
    the_answer106(106, "相关的问题可能的浮出水面", "Related Issues May Surface"),
    the_answer107(107, "保持灵活", "Remain Flexible"),
    the_answer108(108, "删除你自己的障碍物", "Remove Your Own Obstacles"),
    the_answer109(109, "重新确定优先次序什么是重要的", "Reprioritize What Is Important"),
    the_answer110(110, "尊重规则", "Respect The Rules"),
    the_answer111(111, "保存你的精力", "Save Your Energy"),
    the_answer112(112, "寻找更多的选择", "Seek Out More Options"),
    the_answer113(113, "设定优先等级是一个必要的过程！", "Setting Priorities Will Be A Necessary Part Of The Process"),
    the_answer114(114, "很快就会解决它", "Settle It Soon"),
    the_answer115(115, "转移你的焦点", "Shift Your Focus"),
    the_answer116(116, "说出来吧", "Speak Up About It"),
    the_answer117(117, "令人震惊的事件可能发生的", "Startling Events May Occur As A Result"),
    the_answer118(118, "冒险一试", "Take A Chance"),
    the_answer119(119, "负责", "Take Charge"),
    the_answer120(120, "花更多的时间来决定", "Take More Time To Decide"),
    the_answer121(121, "告诉别人它对你意味着什么", "Tell Someone What It Means To You"),
    the_answer122(122, "那将是浪费钱", "That Would Be A Waste Of Money"),
    the_answer123(123, "那是脱离你的控制", "That's Out Of Your Control"),
    the_answer124(124, "答案就在你的后院", "The Answer Is In Your Backyard"),
    the_answer125(125, "答案可能会在另一种语言", "The Answer May Come To You In Another Language"),
    the_answer126(126, "最好的解决办法可能不是明显的", "The Best Solution May Not Be The Obvious One"),
    the_answer127(127, "机会不会很快再来", "The Chance Will Not Come Again Soon"),
    the_answer128(128, "情况将很快发生改变", " The Circumstances Will Change Very Quickly"),
    the_answer129(129, "结果会是好的", "The Outcome Will Be Positive"),
    the_answer130(130, "情况不明", "The Situation Is Unclear"),
    the_answer131(131, "与另一种情况有潜在的联系", "There Is A Substantial Link To Another Situation"),
    the_answer132(132, "有充分的理由保持乐观", "There Is Good Reason To Be Optimistic"),
    the_answer133(133, "没有保证", "There Is No Guarantee"),
    the_answer134(134, "会有障碍要克服", "There Will Be Obstacles To Overcome"),
    the_answer135(135, "这是一个很好的时机，来制定新计划", "This Is A Good Time To Make A New Plan"),
    the_answer136(136, "为了确保能作出最佳决策，需要保持冷静", "To Ensure The Best Decision, Be Calm"),
    the_answer137(137, "相信自己的直觉", "Trust Your Intuition"),
    the_answer138(138, "相信你的原始思想", "Trust Your Original Thought"),
    the_answer139(139, "尝试一种更不太可能的解决方案", "Try A More Unlikely Solution"),
    the_answer140(140, "不宜在这个时候", "Unfavorable At This Time"),
    the_answer141(141, "毫无疑问", "Unquestionably"),
    the_answer142(142, "无论如何你可以提升", "Upgrade Any Way You Can"),
    the_answer143(143, "运用你的想象力", "Use Your Imagination"),
    the_answer144(144, "等一等", "Wait"),
    the_answer145(145, "等待一个更好的机会", "Wait For A Better Offer"),
    the_answer146(146, "看看会发生什么", "Watch And See What Happens"),
    the_answer147(147, "注意你的节奏", "Watch Your Step As You Go"),
    the_answer148(148, "不管你做什么，结果将持久", "Whatever You Do The Results Will Be Lasting"),
    the_answer149(149, "可以", "Yes"),
    the_answer150(150, "是的，但不要强迫", "Yes,But Don't Force It"),
    the_answer151(151, "你一定有支持", "You Are Sure To Have Support"),
    the_answer152(152, "你太近的看了", " You Are Too Close To See"),
    the_answer153(153, "你可能觉得自己无法妥协", "You Could Find Yourself Unable To Compromise"),
    the_answer154(154, "你真的不在乎", "You Don't Really Care"),
    the_answer155(155, "你知道现在比以前更好", "You Know Better Now Than Ever Before"),
    the_answer156(156, "你可能会反对", "You May Have Opposition"),
    the_answer157(157, "你可能会放弃其他的东西", "You May Have To Drop Other Things"),
    the_answer158(158, "你必须", "You Must"),
    the_answer159(159, "你现在必须行动", "You Must Act Now"),
    the_answer160(160, "你会发现一切你需要知道的", "You Will Find Out Everything You'll Need To Know"),
    the_answer161(161, "你将需要适应", "You Will Need To Accommodate"),
    the_answer162(162, "你不会失望的", "You Will Not Be Disappointed"),
    the_answer163(163, "你会很高兴你做了", "You'll Be Happy You Did"),
    the_answer164(164, "你会得到最后的决定", "You'll Get The Final Word"),
    the_answer165(165, "你将不得不妥协", "You'll Have To Compromise"),
    the_answer166(166, "你将不得不补回来", "You'll Have To Make It Up As You Go"),
    the_answer167(167, "您需要了解更多信息", "You'll Need More Information"),
    the_answer168(168, "你需要考虑其他办法", "You'll Need To Consider Other Ways"),
    the_answer169(169, "你需要主动出击", "You'll Need To Take The Initiative"),
    the_answer170(170, "你会后悔的", "You'll Regret It"),
    the_answer171(171, "别失望", "123"),
    the_answer172(172, "不必为你无法控制的事情而担心", "123"),
    the_answer173(173, "不要忘记微笑", "123"),
    the_answer174(174, "阳光", "123"),
    the_answer175(175, "挥手道别", "123"),
    the_answer176(176, "你失去的某天会以不同的方式归还于你", "123"),
    the_answer177(177, "你的状态很不对", "123"),
    the_answer178(178, "这是个麻烦", "123"),
    the_answer179(179, "你或许需要突破", "123"),
    the_answer180(180, "放弃", "123"),
    the_answer181(181, "你唯一能做的只有把握现在", "123"),
    the_answer182(182, "学会珍惜", "123"),
    the_answer183(183, "改变心情", "123"),
    the_answer184(184, "一直走下去", "123"),
    the_answer185(185, "优秀", "123"),
    the_answer186(186, "坚持不懈的努力", "123"),
    the_answer187(187, "不适合", "123"),
    the_answer188(188, "愉快生活", "123"),
    the_answer189(189, "终点", "123"),
    the_answer190(190, "换一个方向", "123"),
    the_answer191(191, "岁月静好", "123"),
    the_answer192(192, "放轻松,这很简单", "123"),
    the_answer193(193, "早点儿开始", "123"),
    the_answer194(194, "不要后悔", "123"),
    the_answer195(195, "也许会迟到", "123"),
    the_answer196(196, "沉默", "123"),
    the_answer197(197, "好像平凡了点", "123"),
    the_answer198(198, "糊涂一点更好", "123"),
    the_answer199(199, "善待自己", "123"),
    the_answer200(200, "放手", "Perhaps, When You're Older"),
    the_answer201(201, "呼吸一下新鲜空气", "Prepare For The Unexpected"),
    the_answer202(202, "没有答案", "Press For Closure"),
    the_answer203(203, "感恩,运气就会越来越好", "Proceed At A More Relaxed Pace"),
    the_answer204(204, "原谅", "  Realize That Too Many Choices Is As Difficult As Too Few"),
    the_answer205(205, "自我欣赏", "Reconsider Your Approach"),
    the_answer206(206, "复杂的事情简单做", "Related Issues May Surface"),
    the_answer207(207, "学会自己保护自己", "Remain Flexible"),
    the_answer208(208, "奇迹", "Remove Your Own Obstacles"),
    the_answer209(209, "给自己一个肯定", "Reprioritize What Is Important"),
    the_answer210(210, "甜", "Respect The Rules"),
    the_answer211(211, "保证心态", "Save Your Energy"),
    the_answer212(212, "种下满足，收获幸福", "Seek Out More Options"),
    the_answer213(213, "把握现在", "Setting Priorities Will Be A Necessary Part Of The Process"),
    the_answer214(214, "学会好奇", "Settle It Soon"),
    the_answer215(215, "最美丽的一天", "Shift Your Focus"),
    the_answer216(216, "彼岸", "Speak Up About It"),
    the_answer217(217, "停止", "Startling Events May Occur As A Result"),
    the_answer218(218, "坚强", "Take A Chance"),
    the_answer219(219, "永恒", "Take Charge"),
    the_answer220(220, "常常是最后一把钥匙打开了神殿门", "Take More Time To Decide"),
    the_answer221(221, "不要刻意隐藏", "Tell Someone What It Means To You"),
    the_answer222(222, "停止悲伤", "That Would Be A Waste Of Money"),
    the_answer223(223, "不要刻意压抑", "That's Out Of Your Control"),
    the_answer224(224, "背不动的就放下", "The Answer Is In Your Backyard"),
    the_answer225(225, "不要怕", "The Answer May Come To You In Another Language"),
    the_answer226(226, "安静", "The Best Solution May Not Be The Obvious One"),
    the_answer227(227, "想念", "The Chance Will Not Come Again Soon"),
    the_answer228(228, "驻足静立", " The Circumstances Will Change Very Quickly"),
    the_answer229(229, "活下去", "The Outcome Will Be Positive"),
    the_answer230(230, "去爱", "The Situation Is Unclear"),
    the_answer231(231, "回家", "There Is A Substantial Link To Another Situation"),
    the_answer232(232, "未解之谜", "There Is Good Reason To Be Optimistic"),
    the_answer233(233, "陌生人", "There Is No Guarantee"),
    the_answer234(234, "告别", "There Will Be Obstacles To Overcome"),
    the_answer235(235, "本能", "This Is A Good Time To Make A New Plan"),
    the_answer236(236, "取暖", "To Ensure The Best Decision, Be Calm"),
    the_answer237(237, "重逢", "Trust Your Intuition"),
    the_answer238(238, "不要去忘记", "Trust Your Original Thought"),
    the_answer239(239, "自信起来吧", "Try A More Unlikely Solution"),
    the_answer240(240, "爱", "Unfavorable At This Time"),
    the_answer241(241, "接受那些消失的", "Unquestionably"),
    the_answer242(242, "到此为止", "Upgrade Any Way You Can"),
    the_answer243(243, "一步之遥", "Use Your Imagination"),
    the_answer244(244, "保存", "Wait"),
    the_answer245(245, "虚无的关系", "Wait For A Better Offer"),
    the_answer246(246, "时间有限", "Watch And See What Happens"),
    the_answer247(247, "迷失的世界", "Watch Your Step As You Go"),
    the_answer248(248, "慢下来", "Whatever You Do The Results Will Be Lasting"),
    the_answer249(249, "可怕", "Yes"),
    the_answer250(250, "了不起", "Yes,But Don't Force It"),
    the_answer251(251, "一个正在到来的晴天", "You Are Sure To Have Support"),
    the_answer252(252, "好天气", " You Are Too Close To See"),
    the_answer253(253, "旧梦", "You Could Find Yourself Unable To Compromise"),
    the_answer254(254, "挽留", "You Don't Really Care"),
    the_answer255(255, "逆水行舟", "You Know Better Now Than Ever Before"),
    the_answer256(256, "被排挤", "You May Have Opposition"),
    the_answer257(257, "可以期待的未来", "You May Have To Drop Other Things"),
    the_answer258(258, "平平安安", "You Must"),
    the_answer259(259, "会别错的", "You Must Act Now"),
    the_answer260(260, "朴素", "You Will Find Out Everything You'll Need To Know"),
    the_answer261(261, "成为了事实", "You Will Need To Accommodate"),
    the_answer262(262, "萌芽", "You Will Not Be Disappointed"),
    the_answer263(263, "有一些重要的事", "You'll Be Happy You Did"),
    the_answer264(264, "让你泪流满脸的", "You'll Get The Final Word"),
    the_answer265(265, "不知所措", "You'll Have To Compromise"),
    the_answer266(266, "给人依赖", "You'll Have To Make It Up As You Go"),
    the_answer267(267, "对未知前途的期盼", "You'll Need More Information"),
    the_answer268(268, "用平淡的心态去追求", "You'll Need To Consider Other Ways"),
    the_answer269(269, "一切皆有可能", "You'll Need To Take The Initiative"),
    the_answer270(270, "控制自己的情绪", "You'll Regret It"),
    the_answer271(271, "一些顺其自然", "123"),
    the_answer272(272, "一条没有鲜花的道路", "123"),
    the_answer273(273, "得不到别人的认同", "123"),
    the_answer274(274, "暂且不要判断", "123"),
    the_answer275(275, "不要一成不变", "123"),
    the_answer276(276, "学会认错", "123"),
    the_answer277(277, "你祈求的一切顺利", "123"),
    the_answer278(278, "享受全心全意的付出", "123"),
    the_answer279(279, "站在了最重要的地方", "123"),
    the_answer280(280, "捕风捉影", "123"),
    the_answer281(281, "欢天喜地", "123"),
    the_answer282(282, "轮回", "123"),
    the_answer283(283, "你无法继续沉睡", "123"),
    the_answer284(284, "得到了多数的支持", "123"),
    the_answer285(285, "十分好的预感", "123"),
    the_answer286(286, "背叛", "123"),
    the_answer287(287, "盛开", "123"),
    the_answer288(288, "学会改变什么", "123"),
    the_answer289(289, "最划算的交换", "123"),
    the_answer290(290, "退后一厘米", "123"),
    the_answer291(291, "这真是一个奇怪的问题", "123"),
    the_answer292(292, "用力活着", "123"),
    the_answer293(293, "成长", "123"),
    the_answer294(294, "最好的事情正要发生", "123"),
    the_answer295(295, "没有什么是对的", "123"),
    the_answer296(296, "堕落", "123"),
    the_answer297(297, "多余", "123"),
    the_answer298(298, "必须努力奔跑起来", "123"),
    the_answer299(299, "会有人陪着你", "123"),
    the_answer300(300, "驾驭", "Perhaps, When You're Older"),
    the_answer301(301, "站起来去战斗", "Prepare For The Unexpected"),
    the_answer302(302, "不要看轻别人", "Press For Closure"),
    the_answer303(303, "多读一本书", "Proceed At A More Relaxed Pace"),
    the_answer304(304, "下一页才是你的人生答案", "  Realize That Too Many Choices Is As Difficult As Too Few"),
    the_answer305(305, "出发", "Reconsider Your Approach"),
    the_answer306(306, "差不多得了", "Related Issues May Surface"),
    the_answer307(307, "不要给别人添麻烦", "Remain Flexible"),
    the_answer308(308, "一个人的细水长流", "Remove Your Own Obstacles"),
    the_answer309(309, "左边", "Reprioritize What Is Important"),
    the_answer310(310, "有人浪费了你的时间", "Respect The Rules"),
    the_answer311(311, "最后什么都没改变", "Save Your Energy"),
    the_answer312(312, "对，去吧", "Seek Out More Options"),
    the_answer313(313, "扔掉这些东西", "Setting Priorities Will Be A Necessary Part Of The Process"),
    the_answer314(314, "有些人开始慌乱", "Settle It Soon"),
    the_answer315(315, "找回自己", "Shift Your Focus"),
    the_answer316(316, "重生", "Speak Up About It"),
    the_answer317(317, "慢些，我们就会更快", "Startling Events May Occur As A Result"),
    the_answer318(318, "一个人的朝圣", "Take A Chance"),
    the_answer319(319, "孤单", "Take Charge"),
    the_answer320(320, "下一个天亮", "Take More Time To Decide"),
    the_answer321(321, "独角戏", "Tell Someone What It Means To You"),
    the_answer322(322, "平凡之路", "That Would Be A Waste Of Money"),
    the_answer323(323, "直面残酷", "That's Out Of Your Control"),
    the_answer324(324, "泡沫", "The Answer Is In Your Backyard"),
    the_answer325(325, "你大概会受点伤", "The Answer May Come To You In Another Language"),
    the_answer326(326, "远行", "The Best Solution May Not Be The Obvious One"),
    the_answer327(327, "一直在找什么", "The Chance Will Not Come Again Soon"),
    the_answer328(328, "回头看看", " The Circumstances Will Change Very Quickly"),
    the_answer329(329, "唤醒沉睡的你", "The Outcome Will Be Positive"),
    the_answer330(330, "也许会有好转", "The Situation Is Unclear"),
    the_answer331(331, "烦恼快要消失了", "There Is A Substantial Link To Another Situation"),
    the_answer332(332, "一无所有", "There Is Good Reason To Be Optimistic"),
    the_answer333(333, "显得有些糖吞", "There Is No Guarantee"),
    the_answer334(334, "迷人的危险", "There Will Be Obstacles To Overcome"),
    the_answer335(335, "结束倒计时", "This Is A Good Time To Make A New Plan"),
    the_answer336(336, "第二次被伤害的机会", "To Ensure The Best Decision, Be Calm"),
    the_answer337(337, "并不会让你高兴", "Trust Your Intuition"),
    the_answer338(338, "没有什么放不下", "Trust Your Original Thought"),
    the_answer339(339, "等待", "Try A More Unlikely Solution"),
    the_answer340(340, "永远不会愈合的伤口", "Unfavorable At This Time"),
    the_answer341(341, "骗不到自己", "Unquestionably"),
    the_answer342(342, "悄然躲开", "Upgrade Any Way You Can"),
    the_answer343(343, "一场完美的悲剧", "Use Your Imagination"),
    the_answer344(344, "寻寻觅觅", "Wait"),
    the_answer345(345, "不要做出任何决定", "Wait For A Better Offer"),
    the_answer346(346, "开心的肯定", "Watch And See What Happens"),
    the_answer347(347, "浪费光阴", "Watch Your Step As You Go"),
    the_answer348(348, "保密", "Whatever You Do The Results Will Be Lasting"),
    the_answer349(349, "被唾弃的决定", "Yes"),
    the_answer350(350, "停止向前", "Yes,But Don't Force It"),
    the_answer351(351, "有点意思", "You Are Sure To Have Support"),
    the_answer352(352, "谢谢", " You Are Too Close To See"),
    the_answer353(353, "再也不用相见", "You Could Find Yourself Unable To Compromise"),
    the_answer354(354, "完美时刻", "You Don't Really Care"),
    the_answer355(355, "会让你痛苦的", "You Know Better Now Than Ever Before"),
    the_answer356(356, "僵持不下", "You May Have Opposition"),
    the_answer357(357, "必不可少", "You May Have To Drop Other Things"),
    the_answer358(358, "对不起", "You Must"),
    the_answer359(359, "试着慷慨一点儿", "You Must Act Now"),
    the_answer360(360, "这不是能犹豫的事儿", "You Will Find Out Everything You'll Need To Know"),
    the_answer361(361, "同意", "You Will Need To Accommodate"),
    the_answer362(362, "试着安静一会", "You Will Not Be Disappointed"),
    the_answer363(363, "默默无闻", "You'll Be Happy You Did"),
    the_answer364(364, "虚空", "You'll Get The Final Word"),
    the_answer365(365, "戒掉过分的急躁", "You'll Have To Compromise"),
    the_answer366(366, "不要隐藏起来", "You'll Have To Make It Up As You Go"),
    the_answer367(367, "其实大家都知道", "You'll Need More Information"),
    the_answer368(368, "会被一直依赖的", "You'll Need To Consider Other Ways"),
    the_answer369(369, "全都给它", "You'll Need To Take The Initiative"),
    the_answer370(370, "坚持了不该坚持的", "You'll Regret It"),
    the_answer371(371, "有点心疼", "123"),
    the_answer372(372, "轻而易举的上海", "123"),
    the_answer373(373, "卑微的等待", "123"),
    the_answer374(374, "你有必要傻一点", "123"),
    the_answer375(375, "一成不变", "123"),
    the_answer376(376, "你会忘记它", "123"),
    the_answer377(377, "禁言", "123"),
    the_answer378(378, "只是一场梦", "123"),
    the_answer379(379, "你要勇敢的离开", "123"),
    the_answer380(380, "拼凑不了的昨天", "123"),
    the_answer381(381, "容易被操控", "123"),
    the_answer382(382, "尽你最大的能力", "123"),
    the_answer383(383, "去忘记", "123"),
    the_answer384(384, "大家好像都不认同", "123"),
    the_answer385(385, "认真起来", "123"),
    the_answer386(386, "值得去做的事", "123"),
    the_answer387(387, "是", "123"),
    the_answer388(388, "白日梦", "123"),
    the_answer389(389, "转个身忘记吧", "123"),
    the_answer390(390, "你可能会比较悲伤", "123"),
    the_answer391(391, "这绝对是个好主意", "123"),
    the_answer392(392, "好的指引", "123"),
    the_answer393(393, "不是", "123"),
    the_answer394(394, "充满未知的迷惑", "123"),
    the_answer395(395, "光明的", "123"),
    the_answer396(396, "幼稚又可笑", "123"),
    the_answer397(397, "你很幸运", "123"),
    the_answer398(398, "机会就在眼前", "123"),
    the_answer399(399, "不如忘掉这个问题", "123"),
    the_answer400(400, "又干净又明亮", "Perhaps, When You're Older"),
    the_answer401(401, "专注一点", "Prepare For The Unexpected"),
    the_answer402(402, "殊途同归", "Press For Closure"),
    the_answer403(403, "背道而驰", "Proceed At A More Relaxed Pace"),
    the_answer404(404, "小迷糊", "  Realize That Too Many Choices Is As Difficult As Too Few"),
    the_answer405(405, "你在开玩笑吗", "Reconsider Your Approach"),
    the_answer406(406, "别难过，你是最棒的", "Related Issues May Surface"),
    the_answer407(407, "吃点东西冷静一下", "Remain Flexible"),
    the_answer408(408, "这个大概会让你哭泣", "Remove Your Own Obstacles"),
    the_answer409(409, "高兴起来吧，你这么厉害", "Reprioritize What Is Important"),
    the_answer410(410, "别总想着过去了", "Respect The Rules"),
    the_answer411(411, "捍卫它", "Save Your Energy"),
    the_answer412(412, "无谓的徘徊", "Seek Out More Options"),
    the_answer413(413, "将要被击溃", "Setting Priorities Will Be A Necessary Part Of The Process"),
    the_answer414(414, "不必耿耿于怀", "Settle It Soon"),
    the_answer415(415, "放在心里吧，这样比较好点", "Shift Your Focus"),
    the_answer416(416, "不用伪装到面目全非", "Speak Up About It"),
    the_answer417(417, "被压抑自己的天性", "Startling Events May Occur As A Result"),
    the_answer418(418, "一个人安安静静待一会儿", "Take A Chance"),
    the_answer419(419, "既然认准这条路，就不要去想走多久", "Take Charge"),
    the_answer420(420, "大哭一场会好受点", "Take More Time To Decide"),
    the_answer421(421, "总会慢慢的过去", "Tell Someone What It Means To You"),
    the_answer422(422, "明天就会有新鲜事发生", "That Would Be A Waste Of Money"),
    the_answer423(423, "这是要靠缘分", "That's Out Of Your Control"),
    the_answer424(424, "太糟糕了", "The Answer Is In Your Backyard"),
    the_answer425(425, "这是起跑线", "The Answer May Come To You In Another Language"),
    the_answer426(426, "没事，有我在", "The Best Solution May Not Be The Obvious One"),
    the_answer427(427, "不要把所有表情写在脸上", "The Chance Will Not Come Again Soon"),
    the_answer428(428, "别人会对你苦笑", " The Circumstances Will Change Very Quickly"),
    the_answer429(429, "好像会很累", "The Outcome Will Be Positive"),
    the_answer430(430, "有人撑着你向前", "The Situation Is Unclear"),
    the_answer431(431, "你需要的只是勇气", "There Is A Substantial Link To Another Situation"),
    the_answer432(432, "不甘心的话就努力争取吧", "There Is Good Reason To Be Optimistic"),
    the_answer433(433, "无条件付出", "There Is No Guarantee"),
    the_answer434(434, "试着更快一点吧", "There Will Be Obstacles To Overcome"),
    the_answer435(435, "这是昂贵的礼物", "This Is A Good Time To Make A New Plan"),
    the_answer436(436, "不能永远一成不变", "To Ensure The Best Decision, Be Calm"),
    the_answer437(437, "甜蜜", "Trust Your Intuition"),
    the_answer438(438, "会有一些困难", "Trust Your Original Thought"),
    the_answer439(439, "等待下一个故事的发生", "Try A More Unlikely Solution"),
    the_answer440(440, "试着面对自己真实的想法", "Unfavorable At This Time"),
    the_answer441(441, "这就是结局", "Unquestionably"),
    the_answer442(442, "心会冷掉", "Upgrade Any Way You Can"),
    the_answer443(443, "愿意并且相信", "Use Your Imagination"),
    the_answer444(444, "守护", "Wait"),
    the_answer445(445, "将要奔赴一场未知的路程", "Wait For A Better Offer"),
    the_answer446(446, "隐忍", "Watch And See What Happens"),
    the_answer447(447, "不必要的退让", "Watch Your Step As You Go"),
    the_answer448(448, "这大概会让你有点寂寞", "Whatever You Do The Results Will Be Lasting"),
    the_answer449(449, "形同陌路", "Yes"),
    the_answer450(450, "不要轻易去相信", "Yes,But Don't Force It"),
    the_answer451(451, "可能会很累", "You Are Sure To Have Support"),
    the_answer452(452, "有些人选择了离开", " You Are Too Close To See"),
    the_answer453(453, "会让周围的人感到温暖", "You Could Find Yourself Unable To Compromise"),
    the_answer454(454, "会有一个阳光明媚的未来", "You Don't Really Care"),
    the_answer455(455, "大概要多想一会", "You Know Better Now Than Ever Before"),
    the_answer456(456, "值得肯定", "You May Have Opposition"),
    the_answer457(457, "好像会有很大的麻烦", "You May Have To Drop Other Things"),
    the_answer458(458, "注意一下周围", "You Must"),
    the_answer459(459, "你将会有好的运气", "You Must Act Now"),
    the_answer460(460, "大概吧", "You Will Find Out Everything You'll Need To Know"),
    the_answer461(461, "漂亮", "You Will Need To Accommodate"),
    the_answer462(462, "你可能会失去一些东西", "You Will Not Be Disappointed"),
    the_answer463(463, "看见的都不是真的", "You'll Be Happy You Did"),
    the_answer464(464, "苦涩", "You'll Get The Final Word"),
    the_answer465(465, "看向未来", "You'll Have To Compromise"),
    the_answer466(466, "笑", "You'll Have To Make It Up As You Go"),
    the_answer467(467, "接受的终将会接受", "You'll Need More Information"),
    the_answer468(468, "保护你的温暖所在", "You'll Need To Consider Other Ways"),
    the_answer469(469, "这就是命", "You'll Need To Take The Initiative"),
    the_answer470(470, "未来会变得特别繁忙", "You'll Regret It"),
    the_answer471(471, "居心叵测", "123"),
    the_answer472(472, "这简直太有趣了", "123"),
    the_answer473(473, "胜券在握", "123"),
    the_answer474(474, "突如其来的幸福", "123"),
    the_answer475(475, "平分秋色", "123"),
    the_answer476(476, "非常融洽", "123"),
    the_answer477(477, "按照一定的规律到达了终点", "123"),
    the_answer478(478, "平衡", "123"),
    the_answer479(479, "残留的遗憾", "123"),
    the_answer480(480, "拜拜", "123"),
    the_answer481(481, "特别的见解", "123"),
    the_answer482(482, "最特别的幸运", "123"),
    the_answer483(483, "值得喝一杯", "123"),
    the_answer484(484, "并不确定真伪", "123"),
    the_answer485(485, "使人警惕起来", "123"),
    the_answer486(486, "空想", "123"),
    the_answer500(487, "你的行动将会改善", "Your Actions Will Improve Thin");

    /** id **/
    private Integer id;

    /** 答案 **/
    private String answer;

    /** 英文答案 **/
    private String englishAnswer;

    private AnswerEnum(Integer id, String answer, String englishAnswer) {
        this.id = id;
        this.answer = answer;
        this.englishAnswer = englishAnswer;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getEnglishAnswer() {
        return englishAnswer;
    }

    public void setEnglishAnswer(String englishAnswer) {
        this.englishAnswer = englishAnswer;
    }

    /**存放全部枚举的缓存对象*/
    private static Map<Integer, AnswerEnum> answerMap = new HashMap<>();
    
    /**将所有枚举缓存*/
    static{
        EnumSet<AnswerEnum> currEnumSet = EnumSet.allOf(AnswerEnum.class);
        
        for (AnswerEnum answerEnum : currEnumSet) {
            answerMap.put(answerEnum.getId(), answerEnum);
        }
    }
    
    /**
     * 
     * Description: 获取map
     * @param
     * @return Map<Integer,AnswerEnum>
     * @throws
     * @Author wangxinbang
     * Create Date: 2017年12月10日 下午4:41:38
     */
    public static Map<Integer, AnswerEnum> getAnswerMap(){
        return answerMap;
    }

}
